### ISSUE TITLE
Featurerequest: Maximum Bitrate Setting

### ISSUE THREAD

**Issue by mojo-hakase** [prof-membrane/plugin.video.funkmediathek#2]
Ich hätte gerne die Möglichkeit, die maximale Bitrate für die Videos im Addon einstellen zu können, da ich das Addon ansonsten mit meiner 16Mbit Leitung nicht wirklich benutzen kann.
Hier die patch-Datei meiner Implementierung:
[plugin.video.funkmediathek.maxbitrate.patch.zip](https://github.com/prof-membrane/plugin.video.funkmediathek/files/652140/plugin.video.funkmediathek.maxbitrate.patch.zip)

**Comment by Bastelbursche** [comment]
So geht es mir auch. Habe auch 16 Mbit/s und die Streams bleiben alle paar Sekunden hängen.

**Comment by prof-membrane** [comment]
https://github.com/prof-membrane/repository.membrane/wiki/Videoqualit%C3%A4t-der-Add-ons#qualit%C3%A4tsauswahl
