### ISSUE TITLE
Funk Mediathek 

### ISSUE THREAD

**Issue by charlybaer0366** [prof-membrane/plugin.video.funkmediathek#3]
Das Addon Funk Mediathek V. 1.2.0 spielt keine gelisteten Einträge dort ab. Scheinbar den Standart dort verändert, weil vorher ohne Fehlermeldung alles wiedergegeben.

**Comment by prof-membrane** [comment]
Fix kommt heute Abend.

**Comment by charlybaer0366** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Funktioniert einwandfrei

Danke

prof-membrane <notifications@github.com> schrieb am 03.03.2017:
>Closed #3.

- -- Diese Nachricht wurde mit K-@ Mail gesendet.
-----BEGIN PGP SIGNATURE-----

iQHOBAEBCgA4MRxDaHJpc3RpYW4gRnJlZHJpY2ggPGNocmlzdGlhbmZyZWRyaWNo
QGdtYWlsLmNvbT4FAli51i8ACgkQKA9YWGrJyJr0sAwAg9mz1oMc3ac0EO7BumWv
yt1MHhvNeS6o0uHoWy1IDN8zvmFPZefolJtI27SQQ089CN3CINrzD1A0WHiFNpaa
utHXogV7CgfbDz8ckKPhOVCr9CQW10dro0KJIuxtyZOHIAfxfuV8X2F2li1o6iBV
Ux92n/wq2MT6XZ7qoAsbT97BMWZP8qNlFq8q1ZH6c/ZvHYUq/jPii+0sHCXMLS12
kbRdPPQWdxPi+S8jxSFx06SG9E4G+oWBx5lUZyP/Jo2gEGlP8hE77RRlc+xgWruB
wt9AtOYynBQr5q57L/vlAABtPW1AEK9hkxObPk8mdgPEgh7F/EqVUFiI/3JNwUtM
tk1dqsQcjuIcSCDfI2pF28dMMlW9OueR3bI4dIflU/b8ItOm7BmQgY0v3ABIxMz4
hJmzSFaq87Imd++OhPYFCltiFiKWM8rGPY8PhTwc0O5GSUhr0SgXvO4o1TKRy1YP
KkhdzPe0eYDJ+bNb0Ea5+oek+OKbbbTR63/QS1QF9W8x
=qOxp
-----END PGP SIGNATURE-----
