### ISSUE TITLE
Einige Serien fehlen im Kodi Funk-Addon

### ISSUE THREAD

**Issue by monarc99** [prof-membrane/plugin.video.funkmediathek#4]
Einen schönen Tag,

einige Serien (z.B. Doctor Who Staffel 3) gibt es momentan nur auf der Webseite.
Diese tauchen nicht in der Android App bzw. deinem Addon auf.

Ich würde vermuten, dass die gerade den Anbieter wechseln. Kann aber auch ein Bug sein.

mfg

**Comment by prof-membrane** [comment]
Wurde schon vor einer halben Stunde mit 1.2.2 behoben.

**Comment by monarc99** [comment]
Wow, bist du schnell 👍 

Danke sehr.
