### ISSUE TITLE
No function at all

### ISSUE THREAD

**Issue by Jockelchen** [prof-membrane/plugin.video.funkmediathek#8]
Doesnt work on kodi anymore.

**Comment by prof-membrane** [comment]
Fixed in my repo.

**Comment by Jockelchen** [comment]
Ok, ich mach es mal kurz. Ich bin ja Kodi noob, wollte das nur einrichten für meine Schwester auf dem FireTV Stick. Und da kommt nach den Änderungen bzg. repo zwar die Anzeige welche Serien ect. vorhanden sind, aber laufen tut trotzdem nichts. 

Ja repo hatte ich schon vorher probiert, ohne kommt ja auch nicht mal eine Anzeige welche Medien vorhanden sind. Wie gesagt, ich noob mach da bestimmt etwas falsch! Hab's auf 17,4 und 18 probiert.

P.s.: Andere Videos funktionieren.
